[[scopes]]
name = "build"
description = "Build related changes"

[[scopes]]
name = "manifests"
description = "Related to manifests of configurations"

[[scopes]]
name = "nix"
description = "Nix files related"

[[scopes]]
name = "ui"
description = "Simple ui changes"

[[scopes]]
name = "database"
description = "Database related changes"

[[scopes]]
name = "api"
description = "Api and db interaction related changes"

[[scopes]]
name = "deps"

[git]
skip_preview = true
skip_emojis = true
