#:schema node_modules/wrangler/config-schema.json
name = "agendate"
compatibility_date = "2025-06-10"
main = "./.output/server/index.mjs"
compatibility_flags = [
  "nodejs_compat",
  "no_nodejs_compat_v2"
]

[assets]
directory = "./.output/public"

[placement]
mode = "smart"

[observability]
enabled = true

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "schedules"
# Change to your test database
database_id = "f6f64e38-333c-4a07-ab68-1813e8aa6872"
